#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier/ESLint standards
yarn lint-staged ||
(
        echo '😤 Get that weak shit out of here! 😤
ESLint/Prettier Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check Typescript standards
yarn tsc --pretty --noEmit || 
(
    echo '🤡❌😂 Failed Type check. 😂❌🤡
Are you seriously trying to write that? Make the changes required above.'
    false;
)

yarn build ||
(
    echo '❌👷🔨❌ Better call Rob... Because your build failed ❌👷🔨❌
Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'